name: Create a GitHub release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create a GitHub Release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          make intel
          mv ddcctl ddcctl-intel
          make nvidia
          mv ddcctl ddcctl-nvidia
          make amd
          mv ddcctl ddcctl-amd
          zip ddcctl.zip ddcctl-intel ddcctl-nvidia ddcctl-amd
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.ref }} release of `ddcctl`.
          draft: false
          prerelease: false
      - name: Upload GitHub Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ddcctl.zip
          asset_name: ddcctl binaries
          asset_content_type: application/zip
